#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from os import path

# activate the virtual environment
activate_this = path.join(path.abspath(path.dirname(__file__)), 'venv/bin/activate_this.py')
with open(activate_this) as f:
    code = compile(f.read(), activate_this, 'exec')
    exec(code, dict(__file__=activate_this))

from tuf_mitm_proxy import arg_parser, create_app

if __name__ == '__main__':
    args = arg_parser(path.basename(__file__)).parse_args()
    create_app(args.proxy_domain, args.proxy_port) \
            .run(debug=True, host=args.bind_interface, port=args.bind_port)
